# Docker compose file for database server deployment
version: '3.8'
services:
  postgres:
    container_name: ptticket-postgres
    hostname: ptticket-postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
      - /var/postgres:/var/lib/postgresql/data
    restart: unless-stopped
  pgadmin:
    container_name: ptticket-pgadmin
    image: elestio/pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ptticket-admin@ptticket.xyz
      PGADMIN_DEFAULT_PASSWORD: hackme
    restart: unless-stopped
  mosquitto-init:
    image: eclipse-mosquitto
    environment:
      - MQTT_ADMIN_USERNAME=$MQTT_ADMIN_USERNAME
      - MQTT_ADMIN_PASSWORD=$MQTT_ADMIN_PASSWORD
      - MQTT_CLEAN=$MQTT_CLEAN
    volumes:
      - ./db/mqtt-init.sh:/mqtt-init.sh
      - /var/mqtt:/mosquitto
    command:
      - /mqtt-init.sh
  mosquitto:
    container_name: ptticket-mqtt
    image: eclipse-mosquitto
    hostname: ptticket-mqtt
    ports:
      - "1883:1883"
      - "8883:8883"
    volumes:
      - ./db/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - /var/mqtt:/mosquitto
      - ./db/mqttcerts:/mqttcerts
    restart: unless-stopped
    depends_on:
      mosquitto-init:
        condition: service_completed_successfully
  auth-watcher:
    container_name: ptticket-auth-watcher
    image: itsmevjnk/ptticket-auth-watcher
    environment:
      - DB_HOST=ptticket-postgres
      - MQTT_HOST=ptticket-mqtt
    restart: unless-stopped
    depends_on:
      mosquitto:
        condition: service_started
      postgres:
        condition: service_started
  dbstatic:
    container_name: ptticket-dbstatic
    image: itsmevjnk/ptticket-dbstatic
    environment:
      - DB_HOST=ptticket-postgres
      - MQTT_HOST=ptticket-mqtt
    depends_on:
      mosquitto:
        condition: service_started
      postgres:
        condition: service_started
  dbapi:
    container_name: ptticket-dbapi
    hostname: ptticket-dbapi
    image: itsmevjnk/ptticket-dbapi
    environment:
      - DB_HOST=ptticket-postgres
      - MQTT_HOST=ptticket-mqtt
    ports:
      - "3101:3000"
  vending:
    container_name: ptticket-vending-dev
    hostname: ptticket-vending
    image: nodered/node-red
    environment:
      - DBAPI_HOST=http://ptticket-dbapi:3000
    volumes:
      - ./docker/nr-vending:/data
    ports:
      - "3102:1880"
  online:
    container_name: ptticket-online
    image: itsmevjnk/ptticket-online
    environment:
      - DATABASE_API=http://ptticket-dbapi:3000/api
      - MQTT_HOST=ptticket-mqtt
    ports:
      - "3103:3000"
  auth:
    container_name: ptticket-auth
    image: itsmevjnk/ptticket-auth
    environment:
      - DB_HOST=ptticket-postgres
      - ADMIN_KEY=c6827a80-5b3e-4d5e-a537-8c5082ee91c2
    ports:
      - "3121:3000"
  sc-vending:
    container_name: ptticket-sc-vending-dev
    image: nodered/node-red
    environment:
      - VENDING_API=http://ptticket-vending:1880/api
    volumes:
      - ./docker/nr-sc-vending:/data
    ports:
      - "3131:1880"
  