# Docker compose file for database server deployment
version: '3.8'
services:
  postgres:
    container_name: ptticket-postgres
    hostname: ptticket-postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
      - /var/postgres:/var/lib/postgresql/data
    restart: unless-stopped
  pgadmin:
    container_name: ptticket-pgadmin
    image: elestio/pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ptticket-admin@ptticket.xyz
      PGADMIN_DEFAULT_PASSWORD: hackme
    restart: unless-stopped
  mosquitto-init:
    image: itsmevjnk/mosquitto
    environment:
      - MQTT_ADMIN_USERNAME=$MQTT_ADMIN_USERNAME
      - MQTT_ADMIN_PASSWORD=$MQTT_ADMIN_PASSWORD
      - MQTT_CLEAN=$MQTT_CLEAN
    volumes:
      - ./mqtt-init.sh:/mqtt-init.sh
      - /var/mqtt:/mosquitto
    command:
      - /mqtt-init.sh
  mosquitto:
    container_name: ptticket-mqtt
    image: itsmevjnk/mosquitto
    hostname: ptticket-mqtt
    ports:
      - "1883:1883"
      - "8883:8883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - /var/mqtt:/mosquitto
      - ./mqttcerts:/mqttcerts
    restart: unless-stopped
    depends_on:
      mosquitto-init:
        condition: service_completed_successfully
  auth-watcher:
    container_name: auth-watcher
    image: itsmevjnk/ptticket-auth-watcher
    environment:
      - DB_HOST=ptticket-postgres
      - MQTT_HOST=ptticket-mqtt
    restart: unless-stopped
    depends_on:
      mosquitto:
        condition: service_started
      postgres:
        condition: service_started
  dbstatic:
    container_name: dbstatic
    image: itsmevjnk/ptticket-dbstatic
    environment:
      - DB_HOST=ptticket-postgres
      - MQTT_HOST=ptticket-mqtt
    ports:
      - "3199:3000"
    depends_on:
      mosquitto:
        condition: service_started
      postgres:
        condition: service_started