version: '3.8'
services:
  mosquitto-init:
    image: eclipse-mosquitto
    environment:
      - MQTT_ADMIN_USERNAME=$MQTT_ADMIN_USERNAME
      - MQTT_ADMIN_PASSWORD=$MQTT_ADMIN_PASSWORD
      - MQTT_CLEAN=$MQTT_CLEAN
    volumes:
      - ./mqtt-init.sh:/mqtt-init.sh
      - /var/mqtt:/mosquitto
    command:
      - /mqtt-init.sh
  mosquitto:
    container_name: ptticket-mqtt
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - /var/mqtt:/mosquitto
    restart: unless-stopped
    depends_on:
      mosquitto-init:
        condition: service_completed_successfully